# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import sidecar_pb2 as sidecar__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sidecar_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SchedulerServiceStub(object):
    """The scheduler service running in the Go component.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetGpuSchedule = channel.unary_unary(
                '/sidecar.SchedulerService/GetGpuSchedule',
                request_serializer=sidecar__pb2.ScheduleRequest.SerializeToString,
                response_deserializer=sidecar__pb2.ScheduleResponse.FromString,
                _registered_method=True)
        self.SubscribeScheduleEvents = channel.unary_stream(
                '/sidecar.SchedulerService/SubscribeScheduleEvents',
                request_serializer=sidecar__pb2.ScheduleRequest.SerializeToString,
                response_deserializer=sidecar__pb2.ScheduleEvent.FromString,
                _registered_method=True)
        self.ReportInferenceStatus = channel.unary_unary(
                '/sidecar.SchedulerService/ReportInferenceStatus',
                request_serializer=sidecar__pb2.InferenceStatusReport.SerializeToString,
                response_deserializer=sidecar__pb2.ScheduleResponse.FromString,
                _registered_method=True)


class SchedulerServiceServicer(object):
    """The scheduler service running in the Go component.
    """

    def GetGpuSchedule(self, request, context):
        """Python polls for current GPU availability.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeScheduleEvents(self, request, context):
        """Go pushes schedule events to Python (server-streaming).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportInferenceStatus(self, request, context):
        """Python reports its inference status to Go.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SchedulerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetGpuSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGpuSchedule,
                    request_deserializer=sidecar__pb2.ScheduleRequest.FromString,
                    response_serializer=sidecar__pb2.ScheduleResponse.SerializeToString,
            ),
            'SubscribeScheduleEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeScheduleEvents,
                    request_deserializer=sidecar__pb2.ScheduleRequest.FromString,
                    response_serializer=sidecar__pb2.ScheduleEvent.SerializeToString,
            ),
            'ReportInferenceStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportInferenceStatus,
                    request_deserializer=sidecar__pb2.InferenceStatusReport.FromString,
                    response_serializer=sidecar__pb2.ScheduleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sidecar.SchedulerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sidecar.SchedulerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SchedulerService(object):
    """The scheduler service running in the Go component.
    """

    @staticmethod
    def GetGpuSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sidecar.SchedulerService/GetGpuSchedule',
            sidecar__pb2.ScheduleRequest.SerializeToString,
            sidecar__pb2.ScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeScheduleEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sidecar.SchedulerService/SubscribeScheduleEvents',
            sidecar__pb2.ScheduleRequest.SerializeToString,
            sidecar__pb2.ScheduleEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportInferenceStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sidecar.SchedulerService/ReportInferenceStatus',
            sidecar__pb2.InferenceStatusReport.SerializeToString,
            sidecar__pb2.ScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
