// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: sidecar.proto

package sidecar

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GPU availability state managed by the scheduler.
type GpuState int32

const (
	GpuState_GPU_STATE_UNKNOWN      GpuState = 0
	GpuState_GPU_STATE_AVAILABLE    GpuState = 1 // Safe for AI inference
	GpuState_GPU_STATE_YIELDING     GpuState = 2 // WindowPoSt deadline approaching, graceful pause
	GpuState_GPU_STATE_WINDOW_POST  GpuState = 3 // WindowPoSt in progress, no inference allowed
	GpuState_GPU_STATE_WINNING_POST GpuState = 4 // WinningPoSt triggered, immediate GPU release
)

// Enum value maps for GpuState.
var (
	GpuState_name = map[int32]string{
		0: "GPU_STATE_UNKNOWN",
		1: "GPU_STATE_AVAILABLE",
		2: "GPU_STATE_YIELDING",
		3: "GPU_STATE_WINDOW_POST",
		4: "GPU_STATE_WINNING_POST",
	}
	GpuState_value = map[string]int32{
		"GPU_STATE_UNKNOWN":      0,
		"GPU_STATE_AVAILABLE":    1,
		"GPU_STATE_YIELDING":     2,
		"GPU_STATE_WINDOW_POST":  3,
		"GPU_STATE_WINNING_POST": 4,
	}
)

func (x GpuState) Enum() *GpuState {
	p := new(GpuState)
	*p = x
	return p
}

func (x GpuState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GpuState) Descriptor() protoreflect.EnumDescriptor {
	return file_sidecar_proto_enumTypes[0].Descriptor()
}

func (GpuState) Type() protoreflect.EnumType {
	return &file_sidecar_proto_enumTypes[0]
}

func (x GpuState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GpuState.Descriptor instead.
func (GpuState) EnumDescriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{0}
}

// Urgency level for yield commands sent to inference service.
type YieldUrgency int32

const (
	YieldUrgency_YIELD_URGENCY_NORMAL    YieldUrgency = 0 // Finish current batch, then pause
	YieldUrgency_YIELD_URGENCY_HIGH      YieldUrgency = 1 // Pause after current request
	YieldUrgency_YIELD_URGENCY_IMMEDIATE YieldUrgency = 2 // Abort in-flight requests, stop now
)

// Enum value maps for YieldUrgency.
var (
	YieldUrgency_name = map[int32]string{
		0: "YIELD_URGENCY_NORMAL",
		1: "YIELD_URGENCY_HIGH",
		2: "YIELD_URGENCY_IMMEDIATE",
	}
	YieldUrgency_value = map[string]int32{
		"YIELD_URGENCY_NORMAL":    0,
		"YIELD_URGENCY_HIGH":      1,
		"YIELD_URGENCY_IMMEDIATE": 2,
	}
)

func (x YieldUrgency) Enum() *YieldUrgency {
	p := new(YieldUrgency)
	*p = x
	return p
}

func (x YieldUrgency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (YieldUrgency) Descriptor() protoreflect.EnumDescriptor {
	return file_sidecar_proto_enumTypes[1].Descriptor()
}

func (YieldUrgency) Type() protoreflect.EnumType {
	return &file_sidecar_proto_enumTypes[1]
}

func (x YieldUrgency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use YieldUrgency.Descriptor instead.
func (YieldUrgency) EnumDescriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{1}
}

// Reason for the schedule event.
type YieldReason int32

const (
	YieldReason_YIELD_REASON_UNKNOWN                 YieldReason = 0
	YieldReason_YIELD_REASON_WINDOW_POST_APPROACHING YieldReason = 1
	YieldReason_YIELD_REASON_WINDOW_POST_ACTIVE      YieldReason = 2
	YieldReason_YIELD_REASON_WINNING_POST            YieldReason = 3
	YieldReason_YIELD_REASON_LOTUS_DISCONNECTED      YieldReason = 4
	YieldReason_YIELD_REASON_MANUAL                  YieldReason = 5
	YieldReason_YIELD_REASON_RESUME                  YieldReason = 6
)

// Enum value maps for YieldReason.
var (
	YieldReason_name = map[int32]string{
		0: "YIELD_REASON_UNKNOWN",
		1: "YIELD_REASON_WINDOW_POST_APPROACHING",
		2: "YIELD_REASON_WINDOW_POST_ACTIVE",
		3: "YIELD_REASON_WINNING_POST",
		4: "YIELD_REASON_LOTUS_DISCONNECTED",
		5: "YIELD_REASON_MANUAL",
		6: "YIELD_REASON_RESUME",
	}
	YieldReason_value = map[string]int32{
		"YIELD_REASON_UNKNOWN":                 0,
		"YIELD_REASON_WINDOW_POST_APPROACHING": 1,
		"YIELD_REASON_WINDOW_POST_ACTIVE":      2,
		"YIELD_REASON_WINNING_POST":            3,
		"YIELD_REASON_LOTUS_DISCONNECTED":      4,
		"YIELD_REASON_MANUAL":                  5,
		"YIELD_REASON_RESUME":                  6,
	}
)

func (x YieldReason) Enum() *YieldReason {
	p := new(YieldReason)
	*p = x
	return p
}

func (x YieldReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (YieldReason) Descriptor() protoreflect.EnumDescriptor {
	return file_sidecar_proto_enumTypes[2].Descriptor()
}

func (YieldReason) Type() protoreflect.EnumType {
	return &file_sidecar_proto_enumTypes[2]
}

func (x YieldReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use YieldReason.Descriptor instead.
func (YieldReason) EnumDescriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{2}
}

// Schedule event pushed from Go scheduler to Python inference service.
type ScheduleEvent struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	State                GpuState               `protobuf:"varint,1,opt,name=state,proto3,enum=sidecar.GpuState" json:"state,omitempty"`
	Urgency              YieldUrgency           `protobuf:"varint,2,opt,name=urgency,proto3,enum=sidecar.YieldUrgency" json:"urgency,omitempty"`
	SecondsUntilDeadline int64                  `protobuf:"varint,3,opt,name=seconds_until_deadline,json=secondsUntilDeadline,proto3" json:"seconds_until_deadline,omitempty"`
	CurrentEpoch         int64                  `protobuf:"varint,4,opt,name=current_epoch,json=currentEpoch,proto3" json:"current_epoch,omitempty"`
	DeadlineOpenEpoch    int64                  `protobuf:"varint,5,opt,name=deadline_open_epoch,json=deadlineOpenEpoch,proto3" json:"deadline_open_epoch,omitempty"`
	Reason               YieldReason            `protobuf:"varint,6,opt,name=reason,proto3,enum=sidecar.YieldReason" json:"reason,omitempty"`
	Message              string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"` // Human-readable description
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ScheduleEvent) Reset() {
	*x = ScheduleEvent{}
	mi := &file_sidecar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleEvent) ProtoMessage() {}

func (x *ScheduleEvent) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleEvent.ProtoReflect.Descriptor instead.
func (*ScheduleEvent) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{0}
}

func (x *ScheduleEvent) GetState() GpuState {
	if x != nil {
		return x.State
	}
	return GpuState_GPU_STATE_UNKNOWN
}

func (x *ScheduleEvent) GetUrgency() YieldUrgency {
	if x != nil {
		return x.Urgency
	}
	return YieldUrgency_YIELD_URGENCY_NORMAL
}

func (x *ScheduleEvent) GetSecondsUntilDeadline() int64 {
	if x != nil {
		return x.SecondsUntilDeadline
	}
	return 0
}

func (x *ScheduleEvent) GetCurrentEpoch() int64 {
	if x != nil {
		return x.CurrentEpoch
	}
	return 0
}

func (x *ScheduleEvent) GetDeadlineOpenEpoch() int64 {
	if x != nil {
		return x.DeadlineOpenEpoch
	}
	return 0
}

func (x *ScheduleEvent) GetReason() YieldReason {
	if x != nil {
		return x.Reason
	}
	return YieldReason_YIELD_REASON_UNKNOWN
}

func (x *ScheduleEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Status report from Python inference service to Go scheduler.
type InferenceStatusReport struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IsRunning         bool                   `protobuf:"varint,1,opt,name=is_running,json=isRunning,proto3" json:"is_running,omitempty"`
	ActiveRequests    int32                  `protobuf:"varint,2,opt,name=active_requests,json=activeRequests,proto3" json:"active_requests,omitempty"`
	GpuUtilizationPct float32                `protobuf:"fixed32,3,opt,name=gpu_utilization_pct,json=gpuUtilizationPct,proto3" json:"gpu_utilization_pct,omitempty"`
	LoadedModel       string                 `protobuf:"bytes,4,opt,name=loaded_model,json=loadedModel,proto3" json:"loaded_model,omitempty"`
	TimestampUnix     int64                  `protobuf:"varint,5,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InferenceStatusReport) Reset() {
	*x = InferenceStatusReport{}
	mi := &file_sidecar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferenceStatusReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferenceStatusReport) ProtoMessage() {}

func (x *InferenceStatusReport) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferenceStatusReport.ProtoReflect.Descriptor instead.
func (*InferenceStatusReport) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{1}
}

func (x *InferenceStatusReport) GetIsRunning() bool {
	if x != nil {
		return x.IsRunning
	}
	return false
}

func (x *InferenceStatusReport) GetActiveRequests() int32 {
	if x != nil {
		return x.ActiveRequests
	}
	return 0
}

func (x *InferenceStatusReport) GetGpuUtilizationPct() float32 {
	if x != nil {
		return x.GpuUtilizationPct
	}
	return 0
}

func (x *InferenceStatusReport) GetLoadedModel() string {
	if x != nil {
		return x.LoadedModel
	}
	return ""
}

func (x *InferenceStatusReport) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

// Request for getting current GPU schedule.
type ScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleRequest) Reset() {
	*x = ScheduleRequest{}
	mi := &file_sidecar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleRequest) ProtoMessage() {}

func (x *ScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleRequest.ProtoReflect.Descriptor instead.
func (*ScheduleRequest) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{2}
}

// Response with current GPU state.
type ScheduleResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	CurrentState           GpuState               `protobuf:"varint,1,opt,name=current_state,json=currentState,proto3,enum=sidecar.GpuState" json:"current_state,omitempty"`
	SecondsUntilNextChange int64                  `protobuf:"varint,2,opt,name=seconds_until_next_change,json=secondsUntilNextChange,proto3" json:"seconds_until_next_change,omitempty"`
	Message                string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ScheduleResponse) Reset() {
	*x = ScheduleResponse{}
	mi := &file_sidecar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleResponse) ProtoMessage() {}

func (x *ScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleResponse.ProtoReflect.Descriptor instead.
func (*ScheduleResponse) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{3}
}

func (x *ScheduleResponse) GetCurrentState() GpuState {
	if x != nil {
		return x.CurrentState
	}
	return GpuState_GPU_STATE_UNKNOWN
}

func (x *ScheduleResponse) GetSecondsUntilNextChange() int64 {
	if x != nil {
		return x.SecondsUntilNextChange
	}
	return 0
}

func (x *ScheduleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_sidecar_proto protoreflect.FileDescriptor

const file_sidecar_proto_rawDesc = "" +
	"\n" +
	"\rsidecar.proto\x12\asidecar\"\xbc\x02\n" +
	"\rScheduleEvent\x12'\n" +
	"\x05state\x18\x01 \x01(\x0e2\x11.sidecar.GpuStateR\x05state\x12/\n" +
	"\aurgency\x18\x02 \x01(\x0e2\x15.sidecar.YieldUrgencyR\aurgency\x124\n" +
	"\x16seconds_until_deadline\x18\x03 \x01(\x03R\x14secondsUntilDeadline\x12#\n" +
	"\rcurrent_epoch\x18\x04 \x01(\x03R\fcurrentEpoch\x12.\n" +
	"\x13deadline_open_epoch\x18\x05 \x01(\x03R\x11deadlineOpenEpoch\x12,\n" +
	"\x06reason\x18\x06 \x01(\x0e2\x14.sidecar.YieldReasonR\x06reason\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\"\xd9\x01\n" +
	"\x15InferenceStatusReport\x12\x1d\n" +
	"\n" +
	"is_running\x18\x01 \x01(\bR\tisRunning\x12'\n" +
	"\x0factive_requests\x18\x02 \x01(\x05R\x0eactiveRequests\x12.\n" +
	"\x13gpu_utilization_pct\x18\x03 \x01(\x02R\x11gpuUtilizationPct\x12!\n" +
	"\floaded_model\x18\x04 \x01(\tR\vloadedModel\x12%\n" +
	"\x0etimestamp_unix\x18\x05 \x01(\x03R\rtimestampUnix\"\x11\n" +
	"\x0fScheduleRequest\"\x9f\x01\n" +
	"\x10ScheduleResponse\x126\n" +
	"\rcurrent_state\x18\x01 \x01(\x0e2\x11.sidecar.GpuStateR\fcurrentState\x129\n" +
	"\x19seconds_until_next_change\x18\x02 \x01(\x03R\x16secondsUntilNextChange\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage*\x89\x01\n" +
	"\bGpuState\x12\x15\n" +
	"\x11GPU_STATE_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13GPU_STATE_AVAILABLE\x10\x01\x12\x16\n" +
	"\x12GPU_STATE_YIELDING\x10\x02\x12\x19\n" +
	"\x15GPU_STATE_WINDOW_POST\x10\x03\x12\x1a\n" +
	"\x16GPU_STATE_WINNING_POST\x10\x04*]\n" +
	"\fYieldUrgency\x12\x18\n" +
	"\x14YIELD_URGENCY_NORMAL\x10\x00\x12\x16\n" +
	"\x12YIELD_URGENCY_HIGH\x10\x01\x12\x1b\n" +
	"\x17YIELD_URGENCY_IMMEDIATE\x10\x02*\xec\x01\n" +
	"\vYieldReason\x12\x18\n" +
	"\x14YIELD_REASON_UNKNOWN\x10\x00\x12(\n" +
	"$YIELD_REASON_WINDOW_POST_APPROACHING\x10\x01\x12#\n" +
	"\x1fYIELD_REASON_WINDOW_POST_ACTIVE\x10\x02\x12\x1d\n" +
	"\x19YIELD_REASON_WINNING_POST\x10\x03\x12#\n" +
	"\x1fYIELD_REASON_LOTUS_DISCONNECTED\x10\x04\x12\x17\n" +
	"\x13YIELD_REASON_MANUAL\x10\x05\x12\x17\n" +
	"\x13YIELD_REASON_RESUME\x10\x062\xfc\x01\n" +
	"\x10SchedulerService\x12E\n" +
	"\x0eGetGpuSchedule\x12\x18.sidecar.ScheduleRequest\x1a\x19.sidecar.ScheduleResponse\x12M\n" +
	"\x17SubscribeScheduleEvents\x12\x18.sidecar.ScheduleRequest\x1a\x16.sidecar.ScheduleEvent0\x01\x12R\n" +
	"\x15ReportInferenceStatus\x12\x1e.sidecar.InferenceStatusReport\x1a\x19.sidecar.ScheduleResponseB0Z.openmodel/go-scheduler/proto/sidecarb\x06proto3"

var (
	file_sidecar_proto_rawDescOnce sync.Once
	file_sidecar_proto_rawDescData []byte
)

func file_sidecar_proto_rawDescGZIP() []byte {
	file_sidecar_proto_rawDescOnce.Do(func() {
		file_sidecar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sidecar_proto_rawDesc), len(file_sidecar_proto_rawDesc)))
	})
	return file_sidecar_proto_rawDescData
}

var file_sidecar_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_sidecar_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_sidecar_proto_goTypes = []any{
	(GpuState)(0),                 // 0: sidecar.GpuState
	(YieldUrgency)(0),             // 1: sidecar.YieldUrgency
	(YieldReason)(0),              // 2: sidecar.YieldReason
	(*ScheduleEvent)(nil),         // 3: sidecar.ScheduleEvent
	(*InferenceStatusReport)(nil), // 4: sidecar.InferenceStatusReport
	(*ScheduleRequest)(nil),       // 5: sidecar.ScheduleRequest
	(*ScheduleResponse)(nil),      // 6: sidecar.ScheduleResponse
}
var file_sidecar_proto_depIdxs = []int32{
	0, // 0: sidecar.ScheduleEvent.state:type_name -> sidecar.GpuState
	1, // 1: sidecar.ScheduleEvent.urgency:type_name -> sidecar.YieldUrgency
	2, // 2: sidecar.ScheduleEvent.reason:type_name -> sidecar.YieldReason
	0, // 3: sidecar.ScheduleResponse.current_state:type_name -> sidecar.GpuState
	5, // 4: sidecar.SchedulerService.GetGpuSchedule:input_type -> sidecar.ScheduleRequest
	5, // 5: sidecar.SchedulerService.SubscribeScheduleEvents:input_type -> sidecar.ScheduleRequest
	4, // 6: sidecar.SchedulerService.ReportInferenceStatus:input_type -> sidecar.InferenceStatusReport
	6, // 7: sidecar.SchedulerService.GetGpuSchedule:output_type -> sidecar.ScheduleResponse
	3, // 8: sidecar.SchedulerService.SubscribeScheduleEvents:output_type -> sidecar.ScheduleEvent
	6, // 9: sidecar.SchedulerService.ReportInferenceStatus:output_type -> sidecar.ScheduleResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_sidecar_proto_init() }
func file_sidecar_proto_init() {
	if File_sidecar_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sidecar_proto_rawDesc), len(file_sidecar_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sidecar_proto_goTypes,
		DependencyIndexes: file_sidecar_proto_depIdxs,
		EnumInfos:         file_sidecar_proto_enumTypes,
		MessageInfos:      file_sidecar_proto_msgTypes,
	}.Build()
	File_sidecar_proto = out.File
	file_sidecar_proto_goTypes = nil
	file_sidecar_proto_depIdxs = nil
}
