// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: sidecar.proto

package sidecar

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SchedulerService_GetGpuSchedule_FullMethodName          = "/sidecar.SchedulerService/GetGpuSchedule"
	SchedulerService_SubscribeScheduleEvents_FullMethodName = "/sidecar.SchedulerService/SubscribeScheduleEvents"
	SchedulerService_ReportInferenceStatus_FullMethodName   = "/sidecar.SchedulerService/ReportInferenceStatus"
)

// SchedulerServiceClient is the client API for SchedulerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The scheduler service running in the Go component.
type SchedulerServiceClient interface {
	// Python polls for current GPU availability.
	GetGpuSchedule(ctx context.Context, in *ScheduleRequest, opts ...grpc.CallOption) (*ScheduleResponse, error)
	// Go pushes schedule events to Python (server-streaming).
	SubscribeScheduleEvents(ctx context.Context, in *ScheduleRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScheduleEvent], error)
	// Python reports its inference status to Go.
	ReportInferenceStatus(ctx context.Context, in *InferenceStatusReport, opts ...grpc.CallOption) (*ScheduleResponse, error)
}

type schedulerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSchedulerServiceClient(cc grpc.ClientConnInterface) SchedulerServiceClient {
	return &schedulerServiceClient{cc}
}

func (c *schedulerServiceClient) GetGpuSchedule(ctx context.Context, in *ScheduleRequest, opts ...grpc.CallOption) (*ScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScheduleResponse)
	err := c.cc.Invoke(ctx, SchedulerService_GetGpuSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerServiceClient) SubscribeScheduleEvents(ctx context.Context, in *ScheduleRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScheduleEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SchedulerService_ServiceDesc.Streams[0], SchedulerService_SubscribeScheduleEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ScheduleRequest, ScheduleEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SchedulerService_SubscribeScheduleEventsClient = grpc.ServerStreamingClient[ScheduleEvent]

func (c *schedulerServiceClient) ReportInferenceStatus(ctx context.Context, in *InferenceStatusReport, opts ...grpc.CallOption) (*ScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScheduleResponse)
	err := c.cc.Invoke(ctx, SchedulerService_ReportInferenceStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchedulerServiceServer is the server API for SchedulerService service.
// All implementations must embed UnimplementedSchedulerServiceServer
// for forward compatibility.
//
// The scheduler service running in the Go component.
type SchedulerServiceServer interface {
	// Python polls for current GPU availability.
	GetGpuSchedule(context.Context, *ScheduleRequest) (*ScheduleResponse, error)
	// Go pushes schedule events to Python (server-streaming).
	SubscribeScheduleEvents(*ScheduleRequest, grpc.ServerStreamingServer[ScheduleEvent]) error
	// Python reports its inference status to Go.
	ReportInferenceStatus(context.Context, *InferenceStatusReport) (*ScheduleResponse, error)
	mustEmbedUnimplementedSchedulerServiceServer()
}

// UnimplementedSchedulerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSchedulerServiceServer struct{}

func (UnimplementedSchedulerServiceServer) GetGpuSchedule(context.Context, *ScheduleRequest) (*ScheduleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGpuSchedule not implemented")
}
func (UnimplementedSchedulerServiceServer) SubscribeScheduleEvents(*ScheduleRequest, grpc.ServerStreamingServer[ScheduleEvent]) error {
	return status.Error(codes.Unimplemented, "method SubscribeScheduleEvents not implemented")
}
func (UnimplementedSchedulerServiceServer) ReportInferenceStatus(context.Context, *InferenceStatusReport) (*ScheduleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportInferenceStatus not implemented")
}
func (UnimplementedSchedulerServiceServer) mustEmbedUnimplementedSchedulerServiceServer() {}
func (UnimplementedSchedulerServiceServer) testEmbeddedByValue()                          {}

// UnsafeSchedulerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SchedulerServiceServer will
// result in compilation errors.
type UnsafeSchedulerServiceServer interface {
	mustEmbedUnimplementedSchedulerServiceServer()
}

func RegisterSchedulerServiceServer(s grpc.ServiceRegistrar, srv SchedulerServiceServer) {
	// If the following call panics, it indicates UnimplementedSchedulerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SchedulerService_ServiceDesc, srv)
}

func _SchedulerService_GetGpuSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServiceServer).GetGpuSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulerService_GetGpuSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServiceServer).GetGpuSchedule(ctx, req.(*ScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulerService_SubscribeScheduleEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ScheduleRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SchedulerServiceServer).SubscribeScheduleEvents(m, &grpc.GenericServerStream[ScheduleRequest, ScheduleEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SchedulerService_SubscribeScheduleEventsServer = grpc.ServerStreamingServer[ScheduleEvent]

func _SchedulerService_ReportInferenceStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InferenceStatusReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServiceServer).ReportInferenceStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulerService_ReportInferenceStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServiceServer).ReportInferenceStatus(ctx, req.(*InferenceStatusReport))
	}
	return interceptor(ctx, in, info, handler)
}

// SchedulerService_ServiceDesc is the grpc.ServiceDesc for SchedulerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SchedulerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sidecar.SchedulerService",
	HandlerType: (*SchedulerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGpuSchedule",
			Handler:    _SchedulerService_GetGpuSchedule_Handler,
		},
		{
			MethodName: "ReportInferenceStatus",
			Handler:    _SchedulerService_ReportInferenceStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeScheduleEvents",
			Handler:       _SchedulerService_SubscribeScheduleEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sidecar.proto",
}
